-- 000_baseline_core.sql
-- ============================================================================
-- GENERATED by scripts/generate-baseline.mjs from the live production catalog.
-- Do not hand-edit: regenerate.
--
-- These 19 tables exist in production but had no CREATE TABLE anywhere in
-- supabase/migrations/. They predate this repo's migration history (README: 001-010
-- are legacy, "do not re-apply"), yet migration 001 line 23 already does
-- 'references tenants(id)'. So the repository could not rebuild its own database:
-- a replay onto an empty project failed on the first file.
--
-- Lives in supabase/baseline/, NOT supabase/migrations/: it is not a migration and
-- must never be recorded in the migration ledger as applied.
--
-- THIS IS A REBUILD ARTIFACT, NOT A MIGRATION TO RUN AGAINST PRODUCTION.
-- The table, index and foreign-key sections ARE idempotent. The POLICY section is
-- NOT: it drops and recreates each policy so a rebuild is deterministic. Running
-- that against a live database would churn real RLS policies, so do not.
-- Production already has these 19 tables; this file exists so an EMPTY database
-- can be brought to the same shape.
--
-- Structure only: no data, and no functions/triggers that later migrations own.
-- ============================================================================

-- ── fin_accounts ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fin_accounts (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "type" text NOT NULL,
  "subtype" text,
  "is_bank" boolean DEFAULT false NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT fin_accounts_type_check CHECK ((type = ANY (ARRAY['asset'::text, 'liability'::text, 'equity'::text, 'revenue'::text, 'expense'::text]))),
  CONSTRAINT fin_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT fin_accounts_tenant_id_code_key UNIQUE (tenant_id, code)
);

-- ── close_workspaces ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.close_workspaces (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "name" text NOT NULL,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "status" text DEFAULT 'open'::text NOT NULL,
  "currency" text DEFAULT 'USD'::text NOT NULL,
  "created_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT close_workspaces_status_check CHECK ((status = ANY (ARRAY['open'::text, 'in_review'::text, 'closed'::text]))),
  CONSTRAINT close_workspaces_pkey PRIMARY KEY (id)
);

-- ── exceptions ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.exceptions (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "workspace_id" uuid,
  "exception_type" text NOT NULL,
  "severity" text DEFAULT 'medium'::text NOT NULL,
  "title" text NOT NULL,
  "detail" text,
  "amount" numeric(14,2),
  "account_id" uuid,
  "ref_table" text,
  "ref_id" uuid,
  "ai_reasoning" text,
  "confidence" numeric(4,3) DEFAULT 0 NOT NULL,
  "proposed_action" text,
  "is_risky" boolean DEFAULT false NOT NULL,
  "status" text DEFAULT 'open'::text NOT NULL,
  "resolved_by" uuid,
  "resolved_at" timestamp with time zone,
  "final_treatment" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT exceptions_exception_type_check CHECK ((exception_type = ANY (ARRAY['unmatched_bank_txn'::text, 'duplicate_invoice'::text, 'missing_receipt'::text, 'unusual_spend'::text, 'late_customer_payment'::text, 'uncategorized_txn'::text, 'revenue_payment_mismatch'::text]))),
  CONSTRAINT exceptions_severity_check CHECK ((severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text]))),
  CONSTRAINT exceptions_status_check CHECK ((status = ANY (ARRAY['open'::text, 'approved'::text, 'rejected'::text, 'resolved'::text]))),
  CONSTRAINT exceptions_pkey PRIMARY KEY (id)
);

-- ── audit_evidence ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.audit_evidence (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "workspace_id" uuid,
  "exception_id" uuid,
  "action" text NOT NULL,
  "source_evidence" text,
  "ai_reasoning" text,
  "confidence" numeric(4,3),
  "approver" uuid,
  "approver_name" text,
  "final_treatment" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT audit_evidence_pkey PRIMARY KEY (id)
);

-- ── vendors ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.vendors (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "name" text NOT NULL,
  "email" text,
  "tax_id" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT vendors_pkey PRIMARY KEY (id)
);

-- ── bills ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bills (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "workspace_id" uuid,
  "vendor_id" uuid,
  "bill_number" text NOT NULL,
  "issue_date" date,
  "due_date" date,
  "amount" numeric(14,2) DEFAULT 0 NOT NULL,
  "amount_paid" numeric(14,2) DEFAULT 0 NOT NULL,
  "currency" text DEFAULT 'USD'::text NOT NULL,
  "account_id" uuid,
  "status" text DEFAULT 'open'::text NOT NULL,
  "has_receipt" boolean DEFAULT false NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT bills_status_check CHECK ((status = ANY (ARRAY['open'::text, 'paid'::text, 'partial'::text, 'overdue'::text, 'void'::text]))),
  CONSTRAINT bills_pkey PRIMARY KEY (id)
);

-- ── customers ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.customers (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "name" text NOT NULL,
  "email" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT customers_pkey PRIMARY KEY (id)
);

-- ── invoices ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.invoices (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "workspace_id" uuid,
  "customer_id" uuid,
  "invoice_number" text NOT NULL,
  "issue_date" date,
  "due_date" date,
  "amount" numeric(14,2) DEFAULT 0 NOT NULL,
  "amount_paid" numeric(14,2) DEFAULT 0 NOT NULL,
  "currency" text DEFAULT 'USD'::text NOT NULL,
  "status" text DEFAULT 'open'::text NOT NULL,
  "has_pdf" boolean DEFAULT false NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT invoices_status_check CHECK ((status = ANY (ARRAY['open'::text, 'paid'::text, 'partial'::text, 'overdue'::text, 'void'::text]))),
  CONSTRAINT invoices_pkey PRIMARY KEY (id)
);

-- ── payments ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.payments (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "workspace_id" uuid,
  "direction" text NOT NULL,
  "source" text,
  "amount" numeric(14,2) DEFAULT 0 NOT NULL,
  "currency" text DEFAULT 'USD'::text NOT NULL,
  "paid_date" date,
  "invoice_id" uuid,
  "bill_id" uuid,
  "external_ref" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT payments_direction_check CHECK ((direction = ANY (ARRAY['inbound'::text, 'outbound'::text]))),
  CONSTRAINT payments_pkey PRIMARY KEY (id)
);

-- ── bank_transactions ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bank_transactions (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "workspace_id" uuid,
  "account_id" uuid,
  "txn_date" date,
  "description" text,
  "amount" numeric(14,2) DEFAULT 0 NOT NULL,
  "category" text,
  "matched_payment_id" uuid,
  "is_matched" boolean DEFAULT false NOT NULL,
  "external_ref" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT bank_transactions_pkey PRIMARY KEY (id)
);

-- ── close_tasks ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.close_tasks (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "workspace_id" uuid,
  "title" text NOT NULL,
  "category" text,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT close_tasks_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'blocked'::text, 'done'::text]))),
  CONSTRAINT close_tasks_pkey PRIMARY KEY (id)
);

-- ── tenants ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tenants (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "plan" text DEFAULT 'starter'::text NOT NULL,
  "status" text DEFAULT 'active'::text NOT NULL,
  "industry" text,
  "accent_color" text DEFAULT '#6366f1'::text,
  "logo_url" text,
  "settings" jsonb DEFAULT '{}'::jsonb,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "monthly_token_budget" integer DEFAULT 5000000 NOT NULL,
  "parent_tenant_id" uuid,
  "allow_self_serve_subtenants" boolean DEFAULT false NOT NULL,
  "trial_ends_at" timestamp with time zone,
  "vocabulary" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "admin_name" text,
  "admin_email" text,
  "billing_email" text,
  "billing_contact_name" text,
  "adoption_score" numeric(5,2) DEFAULT 0,
  "knowledge_review_interval_days" integer,
  CONSTRAINT tenants_not_self_parent CHECK ((id IS DISTINCT FROM parent_tenant_id)),
  CONSTRAINT tenants_plan_check CHECK ((plan = ANY (ARRAY['starter'::text, 'growth'::text, 'enterprise'::text]))),
  CONSTRAINT tenants_status_check CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text, 'trial'::text]))),
  CONSTRAINT tenants_pkey PRIMARY KEY (id),
  CONSTRAINT tenants_slug_key UNIQUE (slug)
);

-- ── conversations ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.conversations (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "channel" text DEFAULT 'chat'::text NOT NULL,
  "status" text DEFAULT 'open'::text NOT NULL,
  "subject" text,
  "customer_name" text,
  "customer_email" text,
  "assigned_to" uuid,
  "sentiment" text,
  "confidence_score" numeric(4,3),
  "resolution_type" text,
  "tags" text[] DEFAULT '{}'::text[],
  "metadata" jsonb DEFAULT '{}'::jsonb,
  "opened_at" timestamp with time zone DEFAULT now(),
  "resolved_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "csat_score" smallint,
  "csat_submitted_at" timestamp with time zone,
  CONSTRAINT conversations_channel_check CHECK ((channel = ANY (ARRAY['chat'::text, 'email'::text, 'phone'::text, 'api'::text]))),
  CONSTRAINT conversations_csat_score_check CHECK ((csat_score = ANY (ARRAY[1, '-1'::integer]))),
  CONSTRAINT conversations_resolution_type_check CHECK ((resolution_type = ANY (ARRAY['auto_resolved'::text, 'agent_assisted'::text, 'escalated'::text, 'unresolved'::text]))),
  CONSTRAINT conversations_sentiment_check CHECK ((sentiment = ANY (ARRAY['positive'::text, 'neutral'::text, 'negative'::text, 'urgent'::text]))),
  CONSTRAINT conversations_status_check CHECK ((status = ANY (ARRAY['open'::text, 'pending'::text, 'resolved'::text, 'escalated'::text, 'closed'::text]))),
  CONSTRAINT conversations_pkey PRIMARY KEY (id)
);

-- ── escalations ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.escalations (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "conversation_id" uuid,
  "reason" text NOT NULL,
  "question" text,
  "draft_answer" text,
  "confidence" numeric(4,3),
  "status" text DEFAULT 'open'::text NOT NULL,
  "assigned_to" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "resolved_at" timestamp with time zone,
  CONSTRAINT escalations_reason_check CHECK ((reason = ANY (ARRAY['low_confidence'::text, 'no_answer'::text, 'audit_failed'::text, 'customer_request'::text]))),
  CONSTRAINT escalations_status_check CHECK ((status = ANY (ARRAY['open'::text, 'assigned'::text, 'resolved'::text]))),
  CONSTRAINT escalations_pkey PRIMARY KEY (id)
);

-- ── fin_documents ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.fin_documents (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "workspace_id" uuid,
  "doc_type" text NOT NULL,
  "filename" text NOT NULL,
  "storage_path" text,
  "status" text DEFAULT 'uploaded'::text NOT NULL,
  "row_count" integer DEFAULT 0 NOT NULL,
  "ingested_count" integer DEFAULT 0 NOT NULL,
  "parse_summary" text,
  "uploaded_by" uuid,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT fin_documents_doc_type_check CHECK ((doc_type = ANY (ARRAY['general_ledger'::text, 'bank_statement'::text, 'ar_aging'::text, 'ap_aging'::text, 'payroll_summary'::text, 'stripe_export'::text, 'invoice_pdf'::text, 'receipt_pdf'::text, 'other'::text]))),
  CONSTRAINT fin_documents_status_check CHECK ((status = ANY (ARRAY['uploaded'::text, 'parsed'::text, 'ingested'::text, 'needs_review'::text, 'error'::text]))),
  CONSTRAINT fin_documents_pkey PRIMARY KEY (id)
);

-- ── journal_entries ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.journal_entries (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "workspace_id" uuid,
  "entry_date" date,
  "account_id" uuid,
  "memo" text,
  "debit" numeric(14,2) DEFAULT 0 NOT NULL,
  "credit" numeric(14,2) DEFAULT 0 NOT NULL,
  "source" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT journal_entries_pkey PRIMARY KEY (id)
);

-- ── knowledge_articles ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.knowledge_articles (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "tenant_id" uuid NOT NULL,
  "title" text NOT NULL,
  "body" text NOT NULL,
  "summary" text,
  "status" text DEFAULT 'draft'::text NOT NULL,
  "audience" text DEFAULT 'internal'::text NOT NULL,
  "category" text,
  "tags" text[] DEFAULT '{}'::text[],
  "product" text,
  "module" text,
  "quality_score" integer DEFAULT 0,
  "freshness_score" integer DEFAULT 100,
  "view_count" integer DEFAULT 0,
  "helpful_count" integer DEFAULT 0,
  "not_helpful_count" integer DEFAULT 0,
  "embedding" vector(1536),
  "created_by" uuid,
  "published_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "search_tsv" tsvector,
  CONSTRAINT knowledge_articles_audience_check CHECK ((audience = ANY (ARRAY['internal'::text, 'customer'::text, 'both'::text]))),
  CONSTRAINT knowledge_articles_freshness_score_check CHECK (((freshness_score >= 0) AND (freshness_score <= 100))),
  CONSTRAINT knowledge_articles_quality_score_check CHECK (((quality_score >= 0) AND (quality_score <= 100))),
  CONSTRAINT knowledge_articles_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'review'::text, 'published'::text, 'archived'::text]))),
  CONSTRAINT knowledge_articles_pkey PRIMARY KEY (id)
);

-- ── messages ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.messages (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "conversation_id" uuid NOT NULL,
  "tenant_id" uuid NOT NULL,
  "role" text NOT NULL,
  "content" text NOT NULL,
  "confidence_score" numeric(4,3),
  "sources" jsonb DEFAULT '[]'::jsonb,
  "requires_approval" boolean DEFAULT false,
  "approved_by" uuid,
  "approved_at" timestamp with time zone,
  "metadata" jsonb DEFAULT '{}'::jsonb,
  "created_at" timestamp with time zone DEFAULT now(),
  "audit_verdict" text,
  "audit_note" text,
  CONSTRAINT messages_role_check CHECK ((role = ANY (ARRAY['user'::text, 'agent'::text, 'ai'::text, 'system'::text]))),
  CONSTRAINT messages_pkey PRIMARY KEY (id)
);

-- ── profiles ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "tenant_id" uuid,
  "full_name" text,
  "avatar" text,
  "role" text DEFAULT 'agent'::text NOT NULL,
  "layer" text DEFAULT 'tenant'::text NOT NULL,
  "is_active" boolean DEFAULT true,
  "last_seen_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "department" text DEFAULT ''::text NOT NULL,
  "invited_by" text,
  CONSTRAINT profiles_layer_check CHECK ((layer = ANY (ARRAY['platform'::text, 'tenant'::text]))),
  CONSTRAINT profiles_role_check CHECK ((role = ANY (ARRAY['dt_super_admin'::text, 'dt_god_access'::text, 'dt_support'::text, 'dt_billing'::text, 'tenant_owner'::text, 'tenant_admin'::text, 'tenant_manager'::text, 'tenant_user'::text, 'platform_super_admin'::text, 'platform_support'::text, 'platform_billing'::text, 'agent'::text, 'analyst'::text, 'viewer'::text, 'read_only'::text, 'knowledge_manager'::text, 'approver'::text]))),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_key UNIQUE (user_id)
);

-- ── Foreign keys, after every table exists ──────────────────────────────────
DO $$ BEGIN
  ALTER TABLE public.exceptions ADD CONSTRAINT exceptions_account_id_fkey FOREIGN KEY (account_id) REFERENCES fin_accounts(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.exceptions ADD CONSTRAINT exceptions_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES close_workspaces(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.audit_evidence ADD CONSTRAINT audit_evidence_exception_id_fkey FOREIGN KEY (exception_id) REFERENCES exceptions(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.audit_evidence ADD CONSTRAINT audit_evidence_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES close_workspaces(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.bills ADD CONSTRAINT bills_account_id_fkey FOREIGN KEY (account_id) REFERENCES fin_accounts(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.bills ADD CONSTRAINT bills_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.bills ADD CONSTRAINT bills_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES close_workspaces(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.invoices ADD CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.invoices ADD CONSTRAINT invoices_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES close_workspaces(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.payments ADD CONSTRAINT payments_bill_id_fkey FOREIGN KEY (bill_id) REFERENCES bills(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.payments ADD CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.payments ADD CONSTRAINT payments_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES close_workspaces(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.bank_transactions ADD CONSTRAINT bank_transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES fin_accounts(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.bank_transactions ADD CONSTRAINT bank_transactions_matched_payment_id_fkey FOREIGN KEY (matched_payment_id) REFERENCES payments(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.bank_transactions ADD CONSTRAINT bank_transactions_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES close_workspaces(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.close_tasks ADD CONSTRAINT close_tasks_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES close_workspaces(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.tenants ADD CONSTRAINT tenants_parent_tenant_id_fkey FOREIGN KEY (parent_tenant_id) REFERENCES tenants(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.conversations ADD CONSTRAINT conversations_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.conversations ADD CONSTRAINT conversations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.escalations ADD CONSTRAINT escalations_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.fin_documents ADD CONSTRAINT fin_documents_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES close_workspaces(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.journal_entries ADD CONSTRAINT journal_entries_account_id_fkey FOREIGN KEY (account_id) REFERENCES fin_accounts(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.journal_entries ADD CONSTRAINT journal_entries_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES close_workspaces(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.knowledge_articles ADD CONSTRAINT knowledge_articles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.knowledge_articles ADD CONSTRAINT knowledge_articles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.messages ADD CONSTRAINT messages_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.messages ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.messages ADD CONSTRAINT messages_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.profiles ADD CONSTRAINT profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.profiles ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── Indexes ─────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_tenants_parent_tenant_id ON public.tenants USING btree (parent_tenant_id);
CREATE INDEX IF NOT EXISTS escalations_conv_idx ON public.escalations USING btree (conversation_id);
CREATE INDEX IF NOT EXISTS escalations_tenant_status_idx ON public.escalations USING btree (tenant_id, status);
CREATE INDEX IF NOT EXISTS fin_documents_ws_idx ON public.fin_documents USING btree (workspace_id);
CREATE INDEX IF NOT EXISTS ka_embedding_idx ON public.knowledge_articles USING ivfflat (embedding vector_cosine_ops) WITH (lists='100');
CREATE INDEX IF NOT EXISTS knowledge_articles_search_tsv_idx ON public.knowledge_articles USING gin (search_tsv);

-- ── Row Level Security ──────────────────────────────────────────────────────
-- Emitted with the tables because on a multi-tenant system RLS is not a
-- hardening step applied later — a table restored without it is a data leak.
ALTER TABLE public.fin_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.close_workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exceptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bank_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.close_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.escalations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fin_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS fin_accounts_ins ON public.fin_accounts;
CREATE POLICY fin_accounts_ins ON public.fin_accounts FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS fin_accounts_sel ON public.fin_accounts;
CREATE POLICY fin_accounts_sel ON public.fin_accounts FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS fin_accounts_upd ON public.fin_accounts;
CREATE POLICY fin_accounts_upd ON public.fin_accounts FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS close_workspaces_ins ON public.close_workspaces;
CREATE POLICY close_workspaces_ins ON public.close_workspaces FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS close_workspaces_sel ON public.close_workspaces;
CREATE POLICY close_workspaces_sel ON public.close_workspaces FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS close_workspaces_upd ON public.close_workspaces;
CREATE POLICY close_workspaces_upd ON public.close_workspaces FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS exceptions_ins ON public.exceptions;
CREATE POLICY exceptions_ins ON public.exceptions FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS exceptions_sel ON public.exceptions;
CREATE POLICY exceptions_sel ON public.exceptions FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS exceptions_upd ON public.exceptions;
CREATE POLICY exceptions_upd ON public.exceptions FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS audit_evidence_ins ON public.audit_evidence;
CREATE POLICY audit_evidence_ins ON public.audit_evidence FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS audit_evidence_sel ON public.audit_evidence;
CREATE POLICY audit_evidence_sel ON public.audit_evidence FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS audit_evidence_upd ON public.audit_evidence;
CREATE POLICY audit_evidence_upd ON public.audit_evidence FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS vendors_ins ON public.vendors;
CREATE POLICY vendors_ins ON public.vendors FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS vendors_sel ON public.vendors;
CREATE POLICY vendors_sel ON public.vendors FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS vendors_upd ON public.vendors;
CREATE POLICY vendors_upd ON public.vendors FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS bills_ins ON public.bills;
CREATE POLICY bills_ins ON public.bills FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS bills_sel ON public.bills;
CREATE POLICY bills_sel ON public.bills FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS bills_upd ON public.bills;
CREATE POLICY bills_upd ON public.bills FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS customers_ins ON public.customers;
CREATE POLICY customers_ins ON public.customers FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS customers_sel ON public.customers;
CREATE POLICY customers_sel ON public.customers FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS customers_upd ON public.customers;
CREATE POLICY customers_upd ON public.customers FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS invoices_ins ON public.invoices;
CREATE POLICY invoices_ins ON public.invoices FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS invoices_sel ON public.invoices;
CREATE POLICY invoices_sel ON public.invoices FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS invoices_upd ON public.invoices;
CREATE POLICY invoices_upd ON public.invoices FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS payments_ins ON public.payments;
CREATE POLICY payments_ins ON public.payments FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS payments_sel ON public.payments;
CREATE POLICY payments_sel ON public.payments FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS payments_upd ON public.payments;
CREATE POLICY payments_upd ON public.payments FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS bank_transactions_ins ON public.bank_transactions;
CREATE POLICY bank_transactions_ins ON public.bank_transactions FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS bank_transactions_sel ON public.bank_transactions;
CREATE POLICY bank_transactions_sel ON public.bank_transactions FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS bank_transactions_upd ON public.bank_transactions;
CREATE POLICY bank_transactions_upd ON public.bank_transactions FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS close_tasks_ins ON public.close_tasks;
CREATE POLICY close_tasks_ins ON public.close_tasks FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS close_tasks_sel ON public.close_tasks;
CREATE POLICY close_tasks_sel ON public.close_tasks FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS close_tasks_upd ON public.close_tasks;
CREATE POLICY close_tasks_upd ON public.close_tasks FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS tn_sel ON public.tenants;
CREATE POLICY tn_sel ON public.tenants FOR SELECT USING (((id = auth_tenant_id()) OR resolve_platform_capability(auth.uid(), 'tenants.view'::text)));
DROP POLICY IF EXISTS Tenant agents manage conversations ON public.conversations;
CREATE POLICY Tenant agents manage conversations ON public.conversations FOR ALL USING (((tenant_id = auth_tenant_id()) AND auth_has_tenant_role(ARRAY['tenant_admin'::text, 'tenant_manager'::text, 'agent'::text])));
DROP POLICY IF EXISTS Tenant members view conversations ON public.conversations;
CREATE POLICY Tenant members view conversations ON public.conversations FOR SELECT USING ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS cv_ins ON public.conversations;
CREATE POLICY cv_ins ON public.conversations FOR INSERT WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS cv_upd ON public.conversations;
CREATE POLICY cv_upd ON public.conversations FOR UPDATE USING ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS escalations_ins ON public.escalations;
CREATE POLICY escalations_ins ON public.escalations FOR INSERT WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS escalations_sel ON public.escalations;
CREATE POLICY escalations_sel ON public.escalations FOR SELECT USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS escalations_upd ON public.escalations;
CREATE POLICY escalations_upd ON public.escalations FOR UPDATE USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS fin_documents_ins ON public.fin_documents;
CREATE POLICY fin_documents_ins ON public.fin_documents FOR INSERT WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS fin_documents_sel ON public.fin_documents;
CREATE POLICY fin_documents_sel ON public.fin_documents FOR SELECT USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS fin_documents_upd ON public.fin_documents;
CREATE POLICY fin_documents_upd ON public.fin_documents FOR UPDATE USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS journal_entries_ins ON public.journal_entries;
CREATE POLICY journal_entries_ins ON public.journal_entries FOR INSERT TO authenticated WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS journal_entries_sel ON public.journal_entries;
CREATE POLICY journal_entries_sel ON public.journal_entries FOR SELECT TO authenticated USING (((tenant_id = auth_tenant_id()) OR is_platform_admin()));
DROP POLICY IF EXISTS journal_entries_upd ON public.journal_entries;
CREATE POLICY journal_entries_upd ON public.journal_entries FOR UPDATE TO authenticated USING ((tenant_id = auth_tenant_id())) WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS Tenant members read published articles ON public.knowledge_articles;
CREATE POLICY Tenant members read published articles ON public.knowledge_articles FOR SELECT USING (((status = 'published'::text) AND (tenant_id = auth_tenant_id())));
DROP POLICY IF EXISTS Tenant staff manage articles ON public.knowledge_articles;
CREATE POLICY Tenant staff manage articles ON public.knowledge_articles FOR ALL USING (((tenant_id = auth_tenant_id()) AND auth_has_tenant_role(ARRAY['tenant_admin'::text, 'tenant_manager'::text, 'agent'::text])));
DROP POLICY IF EXISTS ka_ins ON public.knowledge_articles;
CREATE POLICY ka_ins ON public.knowledge_articles FOR INSERT WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS ka_upd ON public.knowledge_articles;
CREATE POLICY ka_upd ON public.knowledge_articles FOR UPDATE USING ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS Tenant agents insert messages ON public.messages;
CREATE POLICY Tenant agents insert messages ON public.messages FOR INSERT WITH CHECK (((tenant_id = auth_tenant_id()) AND auth_has_tenant_role(ARRAY['tenant_admin'::text, 'tenant_manager'::text, 'agent'::text])));
DROP POLICY IF EXISTS Tenant members view messages ON public.messages;
CREATE POLICY Tenant members view messages ON public.messages FOR SELECT USING ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS ms_ins ON public.messages;
CREATE POLICY ms_ins ON public.messages FOR INSERT WITH CHECK ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS ms_upd ON public.messages;
CREATE POLICY ms_upd ON public.messages FOR UPDATE USING ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS Platform admins manage all profiles ON public.profiles;
CREATE POLICY Platform admins manage all profiles ON public.profiles FOR ALL USING (is_platform_admin()) WITH CHECK (is_platform_admin());
DROP POLICY IF EXISTS Tenant admins view tenant profiles ON public.profiles;
CREATE POLICY Tenant admins view tenant profiles ON public.profiles FOR SELECT USING ((tenant_id = auth_tenant_id()));
DROP POLICY IF EXISTS Users can update own profile ON public.profiles;
CREATE POLICY Users can update own profile ON public.profiles FOR UPDATE USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS Users can view own profile ON public.profiles;
CREATE POLICY Users can view own profile ON public.profiles FOR SELECT USING ((auth.uid() = user_id));

NOTIFY pgrst, 'reload schema';
