// The 13 pre-built Digital Employees defined in the PRD.
// Organizations enable and configure these — they don't build from scratch.

export interface CatalogDE {
  id: string;
  name: string;
  role: string;
  department: string;
  description: string;
  responsibilities: string[];
  defaultCapabilities: string[];
  defaultKnowledgeSources: string[];
  defaultChannels: string[];
  defaultThreshold: number;
  defaultApprovalRequired: boolean;
  icon: string;
  category: 'Customer' | 'Internal';
  tags: string[];
}

export const DE_CATALOG: CatalogDE[] = [
  {
    id: 'cat_support',
    name: 'Support Specialist',
    role: 'Tier-1 Customer Support',
    department: 'Customer Success',
    description: 'Answers product questions, troubleshoots common issues, retrieves knowledge, and escalates unresolved cases — 24/7.',
    responsibilities: ['Answer product questions', 'Troubleshoot common issues', 'Retrieve knowledge', 'Summarize cases', 'Recommend resolutions', 'Escalate unresolved issues', 'Create support drafts', 'Identify knowledge gaps'],
    defaultCapabilities: ['Search Knowledge Base', 'Reply to customers', 'Create support tickets', 'Escalate to human', 'Look up customer account'],
    defaultKnowledgeSources: ['Product Knowledge Base', 'Release Notes', 'Past Resolved Tickets'],
    defaultChannels: ['chat', 'email'],
    defaultThreshold: 75,
    defaultApprovalRequired: false,
    icon: 'S',
    category: 'Customer',
    tags: ['support', 'customer-facing', 'tier-1'],
  },
  {
    id: 'cat_onboarding',
    name: 'Onboarding Specialist',
    role: 'Customer & Employee Onboarding',
    department: 'Customer Success',
    description: 'Guides new customers and employees through setup, explains product features, tracks onboarding progress, and escalates blockers.',
    responsibilities: ['Guide users through onboarding steps', 'Explain product setup', 'Recommend training materials', 'Track onboarding progress', 'Identify implementation risks', 'Escalate blockers', 'Generate onboarding summaries'],
    defaultCapabilities: ['Search Knowledge Base', 'Reply to customers', 'Send emails', 'Assign training modules', 'Schedule meetings'],
    defaultKnowledgeSources: ['Onboarding Guides', 'Product Knowledge Base', 'HR Policies & Benefits'],
    defaultChannels: ['chat', 'email'],
    defaultThreshold: 80,
    defaultApprovalRequired: false,
    icon: 'O',
    category: 'Customer',
    tags: ['onboarding', 'customer-facing', 'setup'],
  },
  {
    id: 'cat_revenue',
    name: 'Revenue Representative',
    role: 'Business Development & Pipeline',
    department: 'Revenue',
    description: 'Discovers prospects, qualifies leads, drafts personalised outreach, updates CRM, and surfaces pipeline insights for the revenue team.',
    responsibilities: ['Prospect discovery', 'ICP matching', 'Company research', 'Lead qualification', 'Personalised outreach drafting', 'Meeting scheduling support', 'CRM updates', 'Follow-up recommendations', 'Proposal preparation support', 'Expansion opportunity identification'],
    defaultCapabilities: ['Search Knowledge Base', 'Update CRM records', 'Send emails', 'Schedule meetings', 'Run reports'],
    defaultKnowledgeSources: ['Product Knowledge Base', 'API Documentation'],
    defaultChannels: ['internal', 'email'],
    defaultThreshold: 85,
    defaultApprovalRequired: true,
    icon: 'R',
    category: 'Internal',
    tags: ['revenue', 'sales', 'bdr', 'pipeline'],
  },
  {
    id: 'cat_billing',
    name: 'Billing Specialist',
    role: 'Billing & Invoicing Support',
    department: 'Finance',
    description: 'Handles billing questions, generates invoices, looks up payment status, and routes credit or refund requests for approval.',
    responsibilities: ['Answer billing questions', 'Generate invoices', 'Look up payment status', 'Route refund requests', 'Explain subscription plans', 'Escalate disputes'],
    defaultCapabilities: ['Search Knowledge Base', 'Reply to customers', 'Look up customer account', 'Create invoices', 'Issue credits / refunds', 'Escalate to human'],
    defaultKnowledgeSources: ['Finance & Billing Data', 'Product Knowledge Base'],
    defaultChannels: ['chat', 'email'],
    defaultThreshold: 80,
    defaultApprovalRequired: true,
    icon: 'B',
    category: 'Customer',
    tags: ['billing', 'finance', 'payments'],
  },
  {
    id: 'cat_account',
    name: 'Account Specialist',
    role: 'Account Management Support',
    department: 'Customer Success',
    description: 'Manages account-level questions, handles profile changes, team member requests, and surfaces account health to the CS team.',
    responsibilities: ['Answer account questions', 'Handle profile updates', 'Manage team member requests', 'Surface account health signals', 'Route sensitive changes for approval'],
    defaultCapabilities: ['Search Knowledge Base', 'Reply to customers', 'Look up customer account', 'Update CRM records', 'Escalate to human'],
    defaultKnowledgeSources: ['Product Knowledge Base', 'Past Resolved Tickets'],
    defaultChannels: ['chat', 'email'],
    defaultThreshold: 78,
    defaultApprovalRequired: false,
    icon: 'A',
    category: 'Customer',
    tags: ['account', 'customer-facing', 'cs'],
  },
  {
    id: 'cat_knowledge',
    name: 'Knowledge Curator',
    role: 'Knowledge Quality & Governance',
    department: 'Operations',
    description: 'Monitors knowledge freshness, detects gaps from escalations and low-confidence answers, and recommends articles for review.',
    responsibilities: ['Validate knowledge freshness', 'Detect gaps', 'Identify outdated content', 'Recommend improvements', 'Review AI-generated updates', 'Support knowledge approval workflows'],
    defaultCapabilities: ['Search Knowledge Base', 'Run reports', 'Reply to internal staff'],
    defaultKnowledgeSources: ['Product Knowledge Base', 'Release Notes', 'Past Resolved Tickets', 'Internal Runbooks'],
    defaultChannels: ['internal'],
    defaultThreshold: 90,
    defaultApprovalRequired: true,
    icon: 'K',
    category: 'Internal',
    tags: ['knowledge', 'governance', 'internal'],
  },
  {
    id: 'cat_compliance',
    name: 'Compliance Officer',
    role: 'Policy & Risk Validation',
    department: 'Legal & Compliance',
    description: 'Reviews responses for policy alignment, detects regulated content, enforces approval rules, and prevents unauthorized actions.',
    responsibilities: ['Review responses', 'Check policy alignment', 'Detect regulated content', 'Enforce approval rules', 'Prevent unauthorized actions', 'Escalate compliance concerns'],
    defaultCapabilities: ['Search Knowledge Base', 'Reply to internal staff', 'Escalate to human', 'Run reports'],
    defaultKnowledgeSources: ['Legal & Compliance Docs', 'HR Policies & Benefits', 'Internal Runbooks'],
    defaultChannels: ['internal'],
    defaultThreshold: 92,
    defaultApprovalRequired: true,
    icon: 'C',
    category: 'Internal',
    tags: ['compliance', 'legal', 'risk', 'governance'],
  },
  {
    id: 'cat_hr',
    name: 'HR Advisor',
    role: 'HR Policy & People Support',
    department: 'HR & People',
    description: 'Answers HR policy questions, explains benefits and payroll, supports employee onboarding, and routes sensitive matters to the HR team.',
    responsibilities: ['Answer HR policy questions', 'Explain benefits', 'Explain payroll rules', 'Support onboarding', 'Route sensitive matters to HR', 'Escalate compliance-sensitive questions'],
    defaultCapabilities: ['Search Knowledge Base', 'Reply to internal staff', 'Escalate to human', 'Assign training modules'],
    defaultKnowledgeSources: ['HR Policies & Benefits', 'Onboarding Guides', 'Internal Runbooks'],
    defaultChannels: ['chat', 'internal'],
    defaultThreshold: 82,
    defaultApprovalRequired: false,
    icon: 'H',
    category: 'Internal',
    tags: ['hr', 'people', 'benefits', 'payroll'],
  },
  {
    id: 'cat_sales_intel',
    name: 'Sales Intelligence Specialist',
    role: 'Market & Prospect Research',
    department: 'Revenue',
    description: 'Researches prospects, builds account briefs, analyses competitors, and prepares meeting intelligence for the sales team.',
    responsibilities: ['Prospect discovery', 'Company research', 'Competitive intelligence', 'ICP matching', 'Account brief generation', 'Meeting preparation'],
    defaultCapabilities: ['Search Knowledge Base', 'Run reports', 'Update CRM records', 'Reply to internal staff'],
    defaultKnowledgeSources: ['Product Knowledge Base', 'API Documentation', 'Internal Runbooks'],
    defaultChannels: ['internal'],
    defaultThreshold: 80,
    defaultApprovalRequired: false,
    icon: 'I',
    category: 'Internal',
    tags: ['sales', 'intelligence', 'research', 'revenue'],
  },
  {
    id: 'cat_csm',
    name: 'Customer Success Manager',
    role: 'Retention, Adoption & Expansion',
    department: 'Customer Success',
    description: 'Monitors account health, detects renewal risk, surfaces expansion opportunities, and prepares executive summaries for the CS team.',
    responsibilities: ['Account health insights', 'Customer sentiment', 'Adoption summaries', 'Renewal risk detection', 'Expansion recommendations', 'Meeting preparation', 'Executive summaries', 'Success plan assistance'],
    defaultCapabilities: ['Search Knowledge Base', 'Run reports', 'Reply to customers', 'Update CRM records', 'Send emails'],
    defaultKnowledgeSources: ['Product Knowledge Base', 'Past Resolved Tickets', 'Internal Runbooks'],
    defaultChannels: ['chat', 'email', 'internal'],
    defaultThreshold: 78,
    defaultApprovalRequired: false,
    icon: 'M',
    category: 'Customer',
    tags: ['cs', 'retention', 'expansion', 'health'],
  },
  {
    id: 'cat_impl',
    name: 'Implementation Consultant',
    role: 'Customer Implementation & Go-Live',
    department: 'Customer Success',
    description: 'Supports implementation teams with project plans, risk detection, status summaries, dependency tracking, and go-live readiness.',
    responsibilities: ['Implementation plans', 'Customer setup guidance', 'Risk detection', 'Status summaries', 'Dependency tracking', 'Training recommendations', 'Handoff summaries', 'Go-live readiness'],
    defaultCapabilities: ['Search Knowledge Base', 'Reply to customers', 'Reply to internal staff', 'Run reports', 'Send emails'],
    defaultKnowledgeSources: ['Onboarding Guides', 'Product Knowledge Base', 'Internal Runbooks'],
    defaultChannels: ['chat', 'email', 'internal'],
    defaultThreshold: 80,
    defaultApprovalRequired: false,
    icon: 'P',
    category: 'Customer',
    tags: ['implementation', 'onboarding', 'go-live'],
  },
  {
    id: 'cat_training',
    name: 'Training Coach',
    role: 'Learning & Development',
    department: 'HR & People',
    description: 'Creates learning paths, assigns training modules, runs skill gap assessments, delivers coaching, and supports internal certification programs.',
    responsibilities: ['Training content', 'Learning paths', 'Role-based training', 'Knowledge quizzes', 'Skill gap identification', 'Coaching', 'Onboarding programs', 'Internal certification'],
    defaultCapabilities: ['Search Knowledge Base', 'Reply to internal staff', 'Assign training modules', 'Run reports'],
    defaultKnowledgeSources: ['Onboarding Guides', 'HR Policies & Benefits', 'Product Knowledge Base', 'Internal Runbooks'],
    defaultChannels: ['internal', 'chat'],
    defaultThreshold: 80,
    defaultApprovalRequired: false,
    icon: 'T',
    category: 'Internal',
    tags: ['training', 'learning', 'development', 'hr'],
  },
  {
    id: 'cat_finance',
    name: 'Finance Analyst',
    role: 'Finance Operations & Reconciliation',
    department: 'Finance',
    description: 'Assists with reconciliation, detects exceptions, reviews invoices, supports month-end close, and generates financial summaries. All actions are approval-gated.',
    responsibilities: ['Reconciliation assistance', 'Exception detection', 'Invoice review support', 'Transaction classification', 'Month-end close support', 'Financial summary generation'],
    defaultCapabilities: ['Search Knowledge Base', 'Reply to internal staff', 'Run reports', 'Escalate to human'],
    defaultKnowledgeSources: ['Finance & Billing Data', 'Legal & Compliance Docs', 'Internal Runbooks'],
    defaultChannels: ['internal'],
    defaultThreshold: 90,
    defaultApprovalRequired: true,
    icon: 'F',
    category: 'Internal',
    tags: ['finance', 'reconciliation', 'analyst', 'compliance'],
  },
];
