import type { AuthUser, Tenant, Page, UserRole } from '../types';

export const mockTenants: Tenant[] = [
  {
    id: 't1',
    name: 'Acme Corp',
    slug: 'acme',
    primaryColor: '#6366f1',
    plan: 'enterprise',
    status: 'active',
    agentsActive: 8,
    usersCount: 142,
    monthlyTokens: 2400000,
    tokenLimit: 5000000,
    createdAt: '2024-01-15',
    industry: 'SaaS',
    contactEmail: 'admin@acme.com',
  },
  {
    id: 't2',
    name: 'Globex Inc',
    slug: 'globex',
    primaryColor: '#10b981',
    plan: 'growth',
    status: 'active',
    agentsActive: 5,
    usersCount: 67,
    monthlyTokens: 980000,
    tokenLimit: 2000000,
    createdAt: '2024-03-20',
    industry: 'Manufacturing',
    contactEmail: 'it@globex.com',
  },
  {
    id: 't3',
    name: 'Initech Solutions',
    slug: 'initech',
    primaryColor: '#f59e0b',
    plan: 'starter',
    status: 'trial',
    agentsActive: 2,
    usersCount: 18,
    monthlyTokens: 120000,
    tokenLimit: 500000,
    createdAt: '2024-05-01',
    industry: 'Finance',
    contactEmail: 'cto@initech.com',
  },
  {
    id: 't4',
    name: 'Hooli Technologies',
    slug: 'hooli',
    primaryColor: '#ef4444',
    plan: 'enterprise',
    status: 'active',
    agentsActive: 12,
    usersCount: 340,
    monthlyTokens: 8100000,
    tokenLimit: 10000000,
    createdAt: '2023-11-08',
    industry: 'Technology',
    contactEmail: 'ops@hooli.com',
  },
  {
    id: 't5',
    name: 'Pied Piper',
    slug: 'piedpiper',
    primaryColor: '#8b5cf6',
    plan: 'growth',
    status: 'suspended',
    agentsActive: 0,
    usersCount: 22,
    monthlyTokens: 0,
    tokenLimit: 2000000,
    createdAt: '2024-02-14',
    industry: 'SaaS',
    contactEmail: 'admin@piedpiper.com',
  },
  {
    id: 't6',
    name: 'Umbrella Medical',
    slug: 'umbrella',
    primaryColor: '#0ea5e9',
    plan: 'enterprise',
    status: 'active',
    agentsActive: 7,
    usersCount: 89,
    monthlyTokens: 3200000,
    tokenLimit: 5000000,
    createdAt: '2024-04-03',
    industry: 'Healthcare',
    contactEmail: 'digital@umbrella.com',
  },
];

export const mockUsers: AuthUser[] = [
  {
    id: 'u1',
    name: 'Alex Rivera',
    email: 'alex@dreamteam.ai',
    role: 'dt_super_admin',
    avatar: 'AR',
  },
  {
    id: 'u2',
    name: 'Jordan Blake',
    email: 'jordan@dreamteam.ai',
    role: 'dt_god_access',
    avatar: 'JB',
  },
  {
    id: 'u3',
    name: 'Sam Nguyen',
    email: 'sam@dreamteam.ai',
    role: 'dt_support',
    avatar: 'SN',
  },
  {
    id: 'u4',
    name: 'Chris Lee',
    email: 'chris@dreamteam.ai',
    role: 'dt_billing',
    avatar: 'CL',
  },
  {
    id: 'u5',
    name: 'Morgan Chen',
    email: 'morgan@acme.com',
    role: 'tenant_owner',
    tenantId: 't1',
    avatar: 'MC',
  },
  {
    id: 'u6',
    name: 'Taylor Smith',
    email: 'taylor@acme.com',
    role: 'tenant_admin',
    tenantId: 't1',
    avatar: 'TS',
  },
  {
    id: 'u7',
    name: 'Quinn Park',
    email: 'quinn@acme.com',
    role: 'tenant_manager',
    tenantId: 't1',
    avatar: 'QP',
  },
  {
    id: 'u8',
    name: 'Drew Wilson',
    email: 'drew@acme.com',
    role: 'tenant_user',
    tenantId: 't1',
    avatar: 'DW',
  },
  {
    id: 'u9',
    name: 'Jamie Torres',
    email: 'jamie@globex.com',
    role: 'tenant_owner',
    tenantId: 't2',
    avatar: 'JT',
  },
  {
    id: 'u10',
    name: 'Avery Johnson',
    email: 'avery@hooli.com',
    role: 'tenant_owner',
    tenantId: 't4',
    avatar: 'AJ',
  },
];

export const canAccessPage = (role: UserRole, page: Page): boolean => {
  const isDtRole = [
    'dt_super_admin',
    'dt_god_access',
    'dt_support',
    'dt_billing',
  ].includes(role);
  const isTenantRole = [
    'tenant_owner',
    'tenant_admin',
    'tenant_manager',
    'tenant_user',
  ].includes(role);
  const dtOnlyPages = [
    'platform_home',
    'platform_tenants',
    'platform_remote_access',
    'platform_health',
    'platform_revenue',
  ];
  if (dtOnlyPages.includes(page)) return isDtRole;
  return isTenantRole || isDtRole;
};
