import React from 'react';

// Starter draft, not a finished legal document — see the banner below.
// Added during the pre-launch readiness review (2026-07-08): no privacy
// policy existed anywhere in the product despite it processing customer
// data and sending it to third-party AI providers. This is a first pass
// for a lawyer to review before it's treated as real/binding.
const PrivacyPolicyPage = ({ onBack }: { onBack?: () => void }) => (
  <div className="min-h-screen bg-slate-950 text-slate-300 overflow-y-auto">
    <div className="max-w-3xl mx-auto px-6 py-12">
      {onBack && (
        <button onClick={onBack} className="text-sm text-indigo-400 hover:text-indigo-300 mb-6">← Back</button>
      )}

      <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-4 mb-8">
        <p className="text-sm font-medium text-amber-300 mb-1">Draft — not yet reviewed by a lawyer</p>
        <p className="text-xs text-amber-400/80">
          This is a starting-point draft written to reflect what DreamTeam AI actually does today. It is not final
          and should not be relied on as your real privacy policy until reviewed by qualified legal counsel,
          especially if you plan to serve customers in the EU (GDPR), California (CCPA/CPRA), or other regions with
          specific data-protection requirements — the placeholders below need real answers first.
        </p>
      </div>

      <h1 className="text-2xl font-bold text-white mb-2">Privacy Policy</h1>
      <p className="text-sm text-slate-500 mb-8">Last updated: [date] · Effective: [date]</p>

      <div className="space-y-8 text-sm leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-white mb-2">1. What this covers</h2>
          <p>
            This Privacy Policy explains what data DreamTeam AI ("we," "us") collects when you use our service, how
            we use it, and what choices you have. It applies to account data (your organization's own users) and to
            the customer/business data your organization connects to or uploads into the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">2. What we collect</h2>
          <ul className="list-disc list-inside space-y-1 text-slate-400">
            <li><span className="text-slate-300">Account data</span> — name, email, role, and authentication details for you and your team members.</li>
            <li><span className="text-slate-300">Customer/business data</span> — whatever your organization connects or uploads (support tickets, knowledge documents, CRM records, financial data, etc.) so the Service's AI Digital Employees can act on it.</li>
            <li><span className="text-slate-300">Usage data</span> — how the Service is used (pages visited, actions taken, AI responses generated) to operate, secure, and improve it.</li>
            <li><span className="text-slate-300">AI interaction data</span> — questions asked to and answers generated by Digital Employees, retained to power features like knowledge-gap detection and audit trails.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">3. How we use it</h2>
          <p>We use collected data to:</p>
          <ul className="list-disc list-inside mt-2 space-y-1 text-slate-400">
            <li>Provide the Service — including generating AI responses and automating workflows you've configured</li>
            <li>Maintain security, including the audit trail and access-control features built into the Service</li>
            <li>Improve the Service (e.g., detecting gaps in your knowledge base so it can be improved)</li>
            <li>Communicate with you about your account, billing, and support</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">4. Third parties we share data with</h2>
          <p>
            To generate AI responses, the Service sends relevant portions of your data to third-party AI model
            providers — currently Anthropic (Claude), and optionally OpenAI and Google, depending on which providers
            you configure. These providers process the data to generate a response and are bound by their own data
            usage terms. [Placeholder: confirm and link each provider's data-processing terms, and state whether
            any provider is used to train their own models on your data — as of this draft, that should be
            explicitly disabled/opted-out wherever the provider allows it.] We do not sell your data to anyone.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">5. Data retention and deletion</h2>
          <p>
            We retain your data for as long as your account is active. If you close your account or it's
            terminated, [placeholder: state the real retention/deletion window — there is currently no automated
            data-deletion mechanism in the product; this needs to be built to match whatever window this policy
            commits to]. You can request deletion of your account and data at any time by contacting us (Section 9).
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">6. Security</h2>
          <p>
            We use industry-standard safeguards to protect your data, including encrypted connections, role-based
            access controls, and an immutable audit trail of sensitive actions. No system is perfectly secure, and we
            can't guarantee absolute security.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">7. Your rights</h2>
          <p>
            Depending on where you're located, you may have rights to access, correct, export, or delete your
            personal data, and to object to certain uses of it. [Placeholder: if you'll have EU or California users,
            this section needs specific GDPR/CCPA rights language and a real, tested data-export/deletion process —
            not yet built as of this draft.] To exercise these rights, contact us (Section 9).
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">8. Children's privacy</h2>
          <p>The Service is intended for business use and is not directed at children. We do not knowingly collect data from children.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">9. Contact</h2>
          <p>
            Questions about this Privacy Policy, or requests to access/delete your data, can be sent to{' '}
            <a href="mailto:bkhan@outsourcetel.com" className="text-indigo-400 hover:underline">bkhan@outsourcetel.com</a>.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white mb-2">10. Changes to this policy</h2>
          <p>We may update this Privacy Policy from time to time. We'll notify active customers of material changes.</p>
        </section>
      </div>
    </div>
  </div>
);

export default PrivacyPolicyPage;
